// Code generated by ogen, DO NOT EDIT.
package api

type ServiceCreateUserRes interface {
	serviceCreateUserRes()
}

type ServiceDeleteUserRes interface {
	serviceDeleteUserRes()
}

type ServiceGetUserRes interface {
	serviceGetUserRes()
}

type ServiceListUsersRes interface {
	serviceListUsersRes()
}

type ServicePatchUserRes interface {
	servicePatchUserRes()
}

type ServicePutUserRes interface {
	servicePutUserRes()
}
