// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Health implements health operation.
//
// GET /ping
func (UnimplementedHandler) Health(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ServiceCreateUser implements Service_createUser operation.
//
// POST /users/
func (UnimplementedHandler) ServiceCreateUser(ctx context.Context, req *User) (r ServiceCreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ServiceDeleteUser implements Service_deleteUser operation.
//
// DELETE /users/{userId}
func (UnimplementedHandler) ServiceDeleteUser(ctx context.Context, params ServiceDeleteUserParams) (r ServiceDeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ServiceGetUser implements Service_getUser operation.
//
// GET /users/{userId}
func (UnimplementedHandler) ServiceGetUser(ctx context.Context, params ServiceGetUserParams) (r ServiceGetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ServiceListUsers implements Service_listUsers operation.
//
// GET /users/
func (UnimplementedHandler) ServiceListUsers(ctx context.Context) (r ServiceListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ServicePatchUser implements Service_patchUser operation.
//
// PATCH /users/{userId}
func (UnimplementedHandler) ServicePatchUser(ctx context.Context, req *User, params ServicePatchUserParams) (r ServicePatchUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ServicePutUser implements Service_putUser operation.
//
// PUT /users/{userId}
func (UnimplementedHandler) ServicePutUser(ctx context.Context, req *User, params ServicePutUserParams) (r ServicePutUserRes, _ error) {
	return r, ht.ErrNotImplemented
}
