// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	HealthOperation            OperationName = "Health"
	ServiceCreateUserOperation OperationName = "ServiceCreateUser"
	ServiceDeleteUserOperation OperationName = "ServiceDeleteUser"
	ServiceGetUserOperation    OperationName = "ServiceGetUser"
	ServiceListUsersOperation  OperationName = "ServiceListUsers"
	ServicePatchUserOperation  OperationName = "ServicePatchUser"
	ServicePutUserOperation    OperationName = "ServicePutUser"
)
